# Generated by Django 5.1.3 on 2024-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
